const express = require('express');
const router = express.Router();
const userController = require('../controllers/userController');

router.get('/', userController.home);
router.post('/',userController.findBooks);
router.get('/admin', userController.view);
router.post('/admin',userController.find);
router.get('/signin',userController.form);
router.post('/signin',userController.signIn);
router.get('/signout',userController.signOut);
router.get('/registeration',userController.register);
router.post('/registeration',userController.createAcc);
router.get('/deleteuser/:id',userController.deleteuser);
router.get('/profile',userController.showProfile);
router.get('/profile/:id',userController.viewProfile);
router.get('/edituser/:id',userController.loaduser);
router.post('/editProfile/:id',userController.editProfile);
router.get('/wishlist',userController.wishlist);
router.get('/books',userController.showBooks);
router.get('/addbook',userController.addBook);
router.post('/addbook',userController.addBookRec);
router.get('/listbooks/:id',userController.user_books);
router.get('/userss',userController.currUser);
router.get('/sell',userController.sellPage);
router.get('/addToWishlist/:Book_Id',userController.saveBook);
router.get('/removeFromWishlist/:id',userController.removeFromWishList);
router.get('/deleteBook/:id',userController.deleteBook);
router.get('/product/:Book_Id', userController.prod);
router.post('/product/:Book_Id',userController.SendMessage);
router.post('/newsletter',userController.nls);
router.post('/subscribe',userController.sub);
router.post('/home',userController.sort);
router.post('/sortUsers',userController.sortUsers);
router.get('/notifications',userController.notificationPage);
router.get('/banUser/:id',userController.banUser);
router.get('/removeFromNotifications/:id',userController.removeNotification);
router.post('/filter',userController.filter);
router.get('/MessagePage',userController.messagePg);

module.exports = router;
